<a href="https://colab.research.google.com/github/kaigitt/GoogleColab/blob/master/numpy_editor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy exercises


1. ndarrayの作成方法について学習します。（4問）
2. 配列の次元数について学習します。（4問）
3. 配列の参照方法ついて学習します。（6問）
4. 配列の演算方法について学習します。（2問）
5. 配列の論理演算方法について学習します。（4問）
6. 配列の結合・分割方法について学習します。（6問）
7. 配列の統計量算出方法について学習します。 (4問)
8. 日付について学習します。 (6問)
9. その他よく使うメソッドについて学習します。 (5問)
10. 補足問題です。 (11問）


### 0. 事前準備

In [3]:
# こちらのセルを実行してください。
import numpy as np

### 1. ndarrayの作成方法について学習します。（4問）

#### 1.1 「8つの「0」が入る配列を作成してください。」

In [18]:
print(np.zeros(8))

[0. 0. 0. 0. 0. 0. 0. 0.]


#### 1.2 「8つの「0」が入る配列を作成し、5番目の値を「1」に変えてください。」

In [20]:
array_1 = np.zeros(8)
array_1[4] = 1
print(array_1)

[0. 0. 0. 0. 1. 0. 0. 0.]


#### 1.3 「10～49までの数字が昇順で入った配列を作成してください。」

In [23]:
array_1 = np.arange(11, 50)
print(array_1)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 1.4 「0～39までの数字が降順で入った配列を作成してください。」

In [32]:
array_1 = np.arange(0, 40)
print(array_1[::-1])

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### 2. 配列の次元数について学習します。 (4問)

In [33]:
# こちらのセルを実行してください。
# このarrayを元に問題を解いていきます。
array = np.arange(0, 25)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#### 2.1 「上記のarrayを5行5列の配列に整形して、変数に代入して表示してください。」

In [43]:
array_1 = np.reshape(array, (5, 5))
print(array_1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 2.2 「2.1で整形した配列の次元数を表示してください。」

In [38]:
print(array_1.shape)

(5, 5)


#### 2.3 「2.1で整形した配列をもう一度一次元の配列に整形して表示してください。」

In [40]:
print(array_1.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


#### 2.4 「上記のarrayを6行6列の配列にして表示してください。」

In [42]:
array_2 = np.resize(array, (6, 6))
print(array_2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24  0  1  2  3  4]
 [ 5  6  7  8  9 10]]


### 3. 配列の参照について学習します。 (6問)

In [44]:
# こちらのセルを実行してください。
# このarray_1を元に問題を解いていきます。
array_1 = np.arange(0, 25).reshape(5, 5)

display(array_1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 3.1 「array_1の2行目のみを抽出してください。」

In [66]:
print(array_1[1])

[5 6 7 8 9]


#### 3.2 「array_1の3行目の3列目のみを抽出してください。」

In [67]:
print(array_1[2, 3])

13


#### 3.3 「array_1の2\~4行目の2\~3列目のみを抽出してください。」

In [68]:
print(array_1[1:4, 1:3])

[[ 6  7]
 [11 12]
 [16 17]]


#### 3.4 「array_1の要素が奇数かどうかを比較し、結果をbool値で格納した配列を変数に代入して表示してください。」

In [71]:
array_2 = array_1 % 2 == 1
print(array_2)

[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]


#### 3.5 「3.4の比較結果を用いて、array_1の要素のうち奇数のものを抽出して変数に代入して表示してください。」

In [74]:
odd = (array_1[array_1 % 2 == 1])
print(odd)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


#### 3.6 「3.5で抽出した配列を3行4列の配列に整形して表示してください。」

In [78]:
array_3 = np.resize(odd, (3, 4))
print(array_3)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


### 4. 配列の演算について学習します。 (2問)




In [79]:
# こちらのセルを実行してください。
# これらの配列を元に問題を解いていきます。
array_1 = np.arange(0, 25).reshape(5, 5)
array_2 = np.arange(25, 50).reshape(5, 5)

display(array_1)
print('')
display(array_2)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

#### 4.1 「array_1の各要素とarray_2の同じ位置にある各要素を足した結果を表示してください。」

In [80]:
print(array_1 + array_2)

[[25 27 29 31 33]
 [35 37 39 41 43]
 [45 47 49 51 53]
 [55 57 59 61 63]
 [65 67 69 71 73]]


#### 4.2 「array_2の各要素をarray_1の同じ位置にある各要素で引いた結果を表示してください。」

In [81]:
print(array_1 - array_2)

[[-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]]


### 5. 配列の論理演算について学習します。 (4問)

In [82]:
# こちらのセルを実行してください。
# この配列を元に問題を解いていきます。
array_1 = np.arange(0, 25).reshape(5, 5)

display(array_1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 5.1 「array_1の要素が偶数かどうかを比較し、結果をbool値で格納した配列を変数に代入して表示してください。」

In [85]:
even_or_odd = array_1 % 2 == 0
print(even_or_odd)

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]


#### 5.2 「array_1の要素が10より大きいかどうかを比較し、結果をbool値で格納した配列を変数に代入して表示してください。」

In [86]:
over_10 = array_1 > 10
print(over_10)

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


#### 5.3 「5.1, 5.2の結果を用いて、そのどちらかの条件を満たす要素をarray_1から抽出して表示してください。」

In [89]:
print(array_1[(even_or_odd | over_10)])

[ 0  2  4  6  8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


#### 5.4 「5.1, 5.2の結果を用いて、そのどちらの条件も満たす要素をarray_1から抽出して表示してください。」

In [90]:
print(array_1[(even_or_odd & over_10)])

[12 14 16 18 20 22 24]


### 6. 配列の結合・分割方法について学習します。 (6問)

In [91]:
# こちらのセルを実行してください。
# この配列を元に問題を解いていきます。
array_1 = np.arange(0, 25).reshape(5, 5)
array_2 = np.arange(25, 50).reshape(5, 5)

display(array_1)
print('')
display(array_2)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

#### 6.1 「concatenate関数を用いて、上のarray_1とarray_2を行方向に結合してください。」

In [94]:
np.concatenate([array_1, array_2], axis=0)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

#### 6.2 「concatenate関数を用いて、上のarray_1とarray_2を列方向に結合してください。」

In [95]:
np.concatenate([array_1, array_2], axis=1)

array([[ 0,  1,  2,  3,  4, 25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9, 30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14, 35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19, 40, 41, 42, 43, 44],
       [20, 21, 22, 23, 24, 45, 46, 47, 48, 49]])

#### 6.3 「concatenate関数を用いずに、上のarray_1とarray_2を行方向に結合してください。」

In [96]:
np.vstack([array_1, array_2])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

#### 6.4 「concatenate関数を用いずに、上のarray_1とarray_2を列方向に結合してください。」

In [97]:
np.hstack([array_1, array_2])

array([[ 0,  1,  2,  3,  4, 25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9, 30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14, 35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19, 40, 41, 42, 43, 44],
       [20, 21, 22, 23, 24, 45, 46, 47, 48, 49]])

#### 6.5 「次のarray_concatenatedを縦に3つに分割してください。」

In [98]:
# こちらのコードを実行してください。
# この配列を元に問題を解いていきます。
array_concatenated = np.arange(48).reshape(6, -1)
array_concatenated

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [99]:
np.vsplit(array_concatenated, 3)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]),
 array([[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]])]

#### 6.6 「次のarray_concatenatedを横に4つに分割してください」

In [100]:
# こちらのセルを実行してください。
# この配列を元に問題を解いていきます。
array_concatenated = np.arange(48).reshape(6, -1)
array_concatenated

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [101]:
np.hsplit(array_concatenated, 4)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25],
        [32, 33],
        [40, 41]]), array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27],
        [34, 35],
        [42, 43]]), array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29],
        [36, 37],
        [44, 45]]), array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31],
        [38, 39],
        [46, 47]])]

### 7. 配列の統計量計算方法について学習します。 (4問)

In [103]:
# こちらのセルを実行してください。
# この配列を元に問題を解いていきます。
array_1 = np.arange(0, 25).reshape(5, 5)
array_2 = np.arange(25, 50).reshape(5, 5)

display(array_1)
print('')
display(array_2)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

#### 7.1 「array_1の行ごとの平均を計算し、その結果を表示してください。」

In [105]:
print(array_1.mean(axis=1))

[ 2.  7. 12. 17. 22.]


#### 7.2 「array_2の各要素を列に対して合計した結果を表示してください。」

In [106]:
print(array_2.sum(axis=0))

[175 180 185 190 195]


#### 7.3 「array_1の最大値を表示してください。」

In [108]:
print(array_1.max())

24


#### 7.4 「array_1とarray_2を結合し、全体の平均を表示してください。」

In [112]:
array_3 = np.concatenate([array_1, array_2])
print(array_3.mean())

24.5


### 8. 日付について学習します。 (6問)

#### 8.1 「今日の日付を表示してください。」

In [116]:
today = np.datetime64('today', 'D')
today

numpy.datetime64('2022-02-28')

#### 8.2 「明日の日付を表示してください。」

In [123]:
tommorow = today + np.timedelta64(1, "D")

#### 8.3 「昨日の日付を表示してください。」

In [125]:
yesterday = today - np.timedelta64(1, "D")

numpy.datetime64('2022-02-27')

#### 8.4 「2021年4月の日付を全て配列に格納してください」

In [134]:
april = np.arange('2021-04', '2021-05', dtype='datetime64[D]')
april

array(['2021-04-01', '2021-04-02', '2021-04-03', '2021-04-04',
       '2021-04-05', '2021-04-06', '2021-04-07', '2021-04-08',
       '2021-04-09', '2021-04-10', '2021-04-11', '2021-04-12',
       '2021-04-13', '2021-04-14', '2021-04-15', '2021-04-16',
       '2021-04-17', '2021-04-18', '2021-04-19', '2021-04-20',
       '2021-04-21', '2021-04-22', '2021-04-23', '2021-04-24',
       '2021-04-25', '2021-04-26', '2021-04-27', '2021-04-28',
       '2021-04-29', '2021-04-30'], dtype='datetime64[D]')

#### 8.5 「2021年の4月の営業日を全て配列に格納してください。」

In [137]:
print(april[np.is_busday(april)])

['2021-04-01' '2021-04-02' '2021-04-05' '2021-04-06' '2021-04-07'
 '2021-04-08' '2021-04-09' '2021-04-12' '2021-04-13' '2021-04-14'
 '2021-04-15' '2021-04-16' '2021-04-19' '2021-04-20' '2021-04-21'
 '2021-04-22' '2021-04-23' '2021-04-26' '2021-04-27' '2021-04-28'
 '2021-04-29' '2021-04-30']


#### 8.6 「2021年4月の週の初めの日を全て配列に格納してください。」

In [138]:
april = np.arange('2021-04', '2021-05', dtype='datetime64[W]')

### 9. よく使うメソッドについて学習します。 (5問)

#### 9.1 「次のarray_3の最大値のインデックスを取得してください、」

In [10]:
# こちらのセルを実行してください。
# この配列を元に問題を解いていきます。
np.random.seed(0)

array_3 = np.random.randint(0, 100, (5, 6))
array_3

array([[44, 47, 64, 67, 67,  9],
       [83, 21, 36, 87, 70, 88],
       [88, 12, 58, 65, 39, 87],
       [46, 88, 81, 37, 25, 77],
       [72,  9, 20, 80, 69, 79]])

In [11]:
array_3.argmax()

11

#### 9.2 「9.1のarray_3を各列に対して昇順にソートしてください。」

In [141]:
np.sort(array_3, axis=1)

array([[ 9, 44, 47, 64, 67, 67],
       [21, 36, 70, 83, 87, 88],
       [12, 39, 58, 65, 87, 88],
       [25, 37, 46, 77, 81, 88],
       [ 9, 20, 69, 72, 79, 80]])

#### 9.3 「9.1のarray_3を2列目を基準に昇順にソートしてください。」

In [12]:
array_3[:, 1]

array([47, 21, 12, 88,  9])

#### 9.4 「5行5列の単位行列を作成してください。」

In [7]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 9.5 「9.1のarray_3の中で60以上のもののカウントを数えてください。」


In [13]:
np.count_nonzero(array_3 > 60)

17

### 10. 補足問題です。 (11問)

#### 10.1 「0~9までの数字が入った配列を作成してください。」

In [19]:
array_1 = np.arange(10)

#### 10.2 「スライス（:）を使用して、10.1で作成した配列から4~7を格納した配列を取り出して下さい。」

In [21]:
array_1[4:8]

array([4, 5, 6, 7])

#### 10.3 「スライス（:）を使用して、10.1で作成した配列から「マイナス」を使用して3~7を格納した配列を取り出して下さい。」

In [22]:
array_1[-7:-2]

array([3, 4, 5, 6, 7])

#### 10.4 「スライス（:）を使用して、10.1で作成した配列から「マイナス」を使用して0~9を降順に格納した配列を取り出して下さい。」

In [23]:
array_1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 10.5 「スライス（:）を使用して、10.1で作成した配列から2~6を一つ飛ばしで格納した配列を取り出して下さい。」

In [25]:
array_1[2:8:2]

array([2, 4, 6])

#### 10.6 「0～8までの数字が昇順で入った配列を作成し、3×3の行列を作成してください。」

In [30]:
array_1 = np.arange(9).reshape(3,3)
print(array_1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10.7 「3×3の正方行列を作成してください。」

In [33]:
data = np.eye(3)
data_2 = np.identity(3)
print(data)
print(data_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 10.8 「10×10の大きさの、外側だけ値が「1」、内側が全て値が「0」の行列を作成してください。」

In [39]:
data = np.ones((10,10))
data[1:-1,1:-1] = 0
print(data)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 10.9 「下記のような8×8の行列を作成してください。」

| | | | | | | | |
| -- | -- | -- | -- | -- | -- | -- | -- |
| 0| 1| 0| 1| 0| 1| 0| 1|
| 1| 0| 1| 0| 1| 0| 1| 0|
| 0| 1| 0| 1| 0| 1| 0| 1|
| 1| 0| 1| 0| 1| 0| 1| 0|
| 0| 1| 0| 1| 0| 1| 0| 1|
| 1| 0| 1| 0| 1| 0| 1| 0|
| 0| 1| 0| 1| 0| 1| 0| 1|
| 1| 0| 1| 0| 1| 0| 1| 0|

In [44]:
data = np.zeros((8,8))
data[1::2,::2] = 1
data[::2,1::2] = 1
print(data)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 10.10 「0～10までの数字を昇順に並べた配列を作成し、4～8までの数字をマイナスに変えて出力してください。」

In [48]:
data = np.arange(10)
data[(3 > data) & (data <= 8)] *= -1
print(data)

[ 0 -1 -2  3  4  5  6  7  8  9]


#### 10.11 「下記のような行列を作成してください。」

| | | | | |
| -- | -- | -- | -- | -- |
| 0| 1| 2| 3| 4|
| 0| 1| 2| 3| 4|
| 0| 1| 2| 3| 4|
| 0| 1| 2| 3| 4|
| 0| 1| 2| 3| 4|

In [51]:
data = np.zeros((5,5))
data += np.arange(5)
print(data)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
